# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::150870609389:role/eksctl-eksctl-demo-nodegroup-ng-9c-NodeInstanceRole-LU0Jvkfgy2mn
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::150870609389:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-24T04:23:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1268"
  uid: 0e68ea57-9d77-496e-bd6d-04a679b638cd
